### PR TITLE
More trees, wind zones, terrain alterations, and script edits

### PR DESCRIPTION
**Pull request by Brock17**

### CODE REVIEW

**Comment by Kmonk222** [comment]
Why do these commits include files where nothing has changed? Some I don't understand, but file renamed don't need to show up.

**Comment by Brock17** [comment]
I was in a hurry to scaffold this repo, so there are instances where I misnamed files and misplaced assets, etc; small mistakes.

**Comment by Kmonk222** [comment]
Will the version modifiers happen with each commit?

**Comment by Brock17** [comment]
Yes, aa long as the game's actual source code was modified.

**Pull request merged**
