### PR TITLE
Added new atmospheric sounds, hopefully.

### PR DESCRIPTION
**Pull request by Waffeey**
Yo Taylor help pls.

### CODE REVIEW

**Comment by Brock17** [comment]
Give me a moment to check it out.

**Comment by Brock17** [comment]
Where did you save your atmosphere file?

**Comment by Waffeey** [comment]
Replaced the old one in Assets, that's why I have no idea how it's still playing the old sounds ahaha. I can play the file, close it, then try to open the game and it's back to the OG sounds.

**Comment by Brock17** [comment]
Okay, here's what I want you to do:
- Delete the file altogether
- Import the sound asset again, this time with a new name
- Try the process again.  If this doesn't work, create another pull request and I'll help you again.

**Pull request closed without merging**
